# ACM cert must live in us-east-1 for CloudFront; the dev provider is already us-east-1.
data "aws_acm_certificate" "issued" {
  domain      = var.acm_domain
  statuses    = ["ISSUED"]
  most_recent = true
}

data "aws_route53_zone" "primary" {
  name         = var.route53_zone_name
  private_zone = false
}

# AWS-managed CachingOptimized policy — avoids the deprecated forwarded_values block.
data "aws_cloudfront_cache_policy" "caching_optimized" {
  name = "Managed-CachingOptimized"
}

data "aws_region" "current" {}

locals {
  # The browser app's Content-Security-Policy, built from what it actually loads:
  #
  #   script-src  'self', plus Cloudflare Turnstile (the sign-up form's human
  #                       check) and nothing else. The microphone AudioWorklet is
  #                       a static file on this origin
  #                       (apps/web/src/lib/audio/pcmCaptureWorklet.js), not a
  #                       blob: URL, so no other outside script source is allowed
  #   frame-src   Turnstile's challenge iframe, and nothing else
  #   style-src   unsafe-inline + Google Fonts CSS. Radix and sonner inject
  #                       style elements at runtime; there is no nonce plumbing.
  #   font-src    Google Fonts files
  #   connect-src Cognito's API (Amplify sign-in and token refresh), the hosted
  #               UI domain, and the API origins (https:// and wss://)
  #
  # frame-ancestors 'none' replaces X-Frame-Options for clickjacking.
  # The rest is the strictest setting that loads nothing else.
  #
  # Matters beyond the usual reasons here: Amplify keeps the access and 7-day
  # refresh tokens in localStorage, so any script injection is session theft.
  connect_src = join(" ", concat(
    [
      "'self'",
      "https://cognito-idp.${data.aws_region.current.region}.amazonaws.com",
      "https://${var.auth_domain}",
    ],
    var.api_origins,
  ))

  content_security_policy = join("; ", [
    "default-src 'self'",
    # Turnstile, the sign-up form's human check: its script, and the iframe it
    # renders the challenge in. Without frame-src the iframe falls back to
    # default-src 'self' and is blocked silently — the form then waits for a
    # token that never comes.
    "script-src 'self' https://challenges.cloudflare.com",
    "frame-src https://challenges.cloudflare.com",
    "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
    "font-src 'self' https://fonts.gstatic.com",
    "img-src 'self' data:",
    "connect-src ${local.connect_src}",
    "object-src 'none'",
    "base-uri 'self'",
    "form-action 'self'",
    "frame-ancestors 'none'",
  ])
}

# Security headers on every response, which the distribution previously sent
# none of.
#
# A CloudFront Function, NOT a response headers policy. This distribution is on
# the flat-rate Free pricing plan, which allows only AWS-managed response headers
# policies: a custom one (the only kind that can carry a CSP) needs the Business
# plan, and attaching one fails with "Distributions with the Free pricing plan
# can't have the following features: Custom response headers policy". CloudFront
# Functions are included in every plan, so this sends the same headers at no cost.
#
# One caveat that a policy would not have: CloudFront does not run
# viewer-response functions when the origin answers 400 or above, so those error
# pages go out without these headers. They carry no script, so nothing is lost
# that a CSP would have protected.
locals {
  # The CSP header name: enforced, or report-only while a new policy is being
  # proven against the real app.
  csp_header = var.csp_enforce ? "content-security-policy" : "content-security-policy-report-only"

  # Values go through jsonencode, so the single quotes in the CSP cannot break
  # out of the JavaScript string literal.
  security_headers = {
    (local.csp_header) = local.content_security_policy
    # One year, subdomains included. Not `preload`: that is a submission to
    # browser vendors and is effectively irreversible for the whole domain.
    "strict-transport-security" = "max-age=31536000; includeSubDomains"
    "x-content-type-options"    = "nosniff"
    "x-frame-options"           = "DENY"
    "referrer-policy"           = "strict-origin-when-cross-origin"
  }
}

resource "aws_cloudfront_function" "security_headers" {
  name    = "prepilot-security-headers-${var.environment}"
  runtime = "cloudfront-js-2.0"
  comment = "CSP, HSTS and friends for the PrepPilot web app (${var.environment})"
  # Published, so the distribution serves this code rather than the last live
  # version. Without it an edit here would plan cleanly and change nothing.
  publish = true

  code = <<-EOT
    // Generated by infra/terraform/modules/cloudfront. Edit it there, not in the console.
    var HEADERS = ${jsonencode(local.security_headers)};

    function handler(event) {
      var response = event.response;
      for (var name in HEADERS) {
        response.headers[name] = { value: HEADERS[name] };
      }
      return response;
    }
  EOT
}

# Client-side routes. The app uses BrowserRouter, so /signin, /callback and the
# rest exist only in the bundle; S3 has no such keys and would answer 403. Any
# path whose last segment has no dot is rewritten to /index.html before the
# cache lookup, so every route shares one cache entry and one invalidation.
#
# A viewer-request function rather than a custom error response: an error
# response is still a 4xx from the origin, and the security-headers function
# does not run on those, so a deep link would load the app with no CSP.
resource "aws_cloudfront_function" "spa_routes" {
  name    = "prepilot-spa-routes-${var.environment}"
  runtime = "cloudfront-js-2.0"
  comment = "Serve index.html for PrepPilot client-side routes (${var.environment})"
  publish = true

  code = <<-EOT
    // Generated by infra/terraform/modules/cloudfront. Edit it there, not in the console.
    function handler(event) {
      var request = event.request;
      var uri = request.uri;
      if (uri.lastIndexOf(".") <= uri.lastIndexOf("/")) {
        request.uri = "/index.html";
      }
      return request;
    }
  EOT
}

resource "aws_cloudfront_origin_access_control" "frontend" {
  name                              = "preppilot-frontend-${var.environment}"
  description                       = "OAC for PrepPilot frontend bucket (${var.environment})"
  origin_access_control_origin_type = "s3"
  signing_behavior                  = "always"
  signing_protocol                  = "sigv4"
}

resource "aws_cloudfront_distribution" "frontend" {
  enabled             = true
  default_root_object = "index.html"
  aliases             = var.aliases

  lifecycle {
    # web_acl_id is locked to this distribution by an active CloudFront Security
    # Savings Bundle subscription — AWS rejects any attempt to remove/change it
    # via the API, so let it drift instead of fighting it every plan.
    ignore_changes = [web_acl_id]
  }

  origin {
    domain_name              = var.bucket_regional_domain_name
    origin_id                = "s3-frontend"
    origin_access_control_id = aws_cloudfront_origin_access_control.frontend.id
  }

  default_cache_behavior {
    target_origin_id       = "s3-frontend"
    viewer_protocol_policy = "redirect-to-https"
    allowed_methods        = ["GET", "HEAD"]
    cached_methods         = ["GET", "HEAD"]
    compress               = true
    cache_policy_id        = data.aws_cloudfront_cache_policy.caching_optimized.id

    function_association {
      event_type   = "viewer-request"
      function_arn = aws_cloudfront_function.spa_routes.arn
    }

    # Security headers on every response. See the function above.
    function_association {
      event_type   = "viewer-response"
      function_arn = aws_cloudfront_function.security_headers.arn
    }
  }

  restrictions {
    geo_restriction {
      restriction_type = "none"
    }
  }

  viewer_certificate {
    acm_certificate_arn      = data.aws_acm_certificate.issued.arn
    ssl_support_method       = "sni-only"
    minimum_protocol_version = "TLSv1.2_2021"
  }

  tags = {
    Project     = "prepilot"
    Environment = var.environment
  }
}

# Grant only this distribution read access to the private bucket (OAC).
resource "aws_s3_bucket_policy" "frontend_oac" {
  bucket = var.bucket_id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid       = "AllowCloudFrontServicePrincipalReadOnly"
        Effect    = "Allow"
        Principal = { Service = "cloudfront.amazonaws.com" }
        Action    = "s3:GetObject"
        Resource  = "${var.bucket_arn}/*"
        Condition = {
          StringEquals = {
            "AWS:SourceArn" = aws_cloudfront_distribution.frontend.arn
          }
        }
      }
    ]
  })
}

# Apex A record → CloudFront. Also satisfies Cognito's requirement that the
# parent domain (tharunsekar.xyz) resolves before auth.tharunsekar.xyz is created.
#
# Optional, because only one environment can own the apex: dev does, and prod
# would fail on a duplicate record. Any auth.* domain needs the apex to resolve,
# which it does whichever environment owns it.
resource "aws_route53_record" "apex" {
  count = var.create_apex_record ? 1 : 0

  zone_id = data.aws_route53_zone.primary.zone_id
  name    = var.acm_domain
  type    = "A"

  alias {
    name                   = aws_cloudfront_distribution.frontend.domain_name
    zone_id                = aws_cloudfront_distribution.frontend.hosted_zone_id
    evaluate_target_health = false
  }
}

# One A record per subdomain alias (e.g. preppilot-dev.tharunsekar.xyz). The
# apex is excluded because the record above already owns it. The ACM cert's
# *.tharunsekar.xyz SAN covers any single-level subdomain listed here.
resource "aws_route53_record" "subdomain" {
  for_each = toset([for alias in var.aliases : alias if alias != var.acm_domain])

  zone_id = data.aws_route53_zone.primary.zone_id
  name    = each.value
  type    = "A"

  alias {
    name                   = aws_cloudfront_distribution.frontend.domain_name
    zone_id                = aws_cloudfront_distribution.frontend.hosted_zone_id
    evaluate_target_health = false
  }
}

# The apex record became optional (count) when prod arrived. This moves the
# existing record to its new address instead of destroying and recreating the
# apex — which would briefly break tharunsekar.xyz and everything under auth.*.
moved {
  from = aws_route53_record.apex
  to   = aws_route53_record.apex[0]
}
